services:
  redis:
    container_name: promy-redis
    image: redis:7-alpine
    networks:
      - eventbus-network
    ports:
      - "6389:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  redisinsight: #Redis's official GUI
    container_name: promy-redisinsight
    image: redis/redisinsight:latest
    networks:
      - eventbus-network
    ports:
      - "5540:5540"
    depends_on:
      redis:
        condition: service_healthy

networks:
  eventbus-network:
    name: eventbus-network  # force exact name
    driver: bridge

volumes:
  redis-data:
    driver: local
